"""field removed from waybill table

Revision ID: 0cafdafd792e
Revises: b5b248a00ad5
Create Date: 2023-04-19 14:09:27.217985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cafdafd792e'
down_revision = 'b5b248a00ad5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waybill', 'waybill_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waybill', sa.Column('waybill_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
